### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by whitetiger21022014** [noureldien/FingerprintRecognition#2]
Dear Noureldien,
Do you have any document or link for building/installing FingerprintRecognition
Thanks

**Comment by noureldien** [comment]
Hello @whitetiger21022014 
You can easily install the app on most of android phones using the following .apk:
https://github.com/noureldien/FingerprintRecognition/blob/master/Java/bin/classes/FingerprintRecognition.apk
Or you may try this as well:
https://github.com/noureldien/FingerprintRecognition/blob/master/Java/bin/classes/FingerprintRecognition.unaligned.apk

Thanks

**Comment by whitetiger21022014** [comment]
Thanks for your reply
Ex. for comparing ~200.000 pictures and it will take time. So may I compile your code on Linux (ex: Centos/Ubuntu) or Windows?
Thanks

**Comment by noureldien** [comment]
Please check the Matlab code, it works as well.
https://github.com/noureldien/FingerprintRecognition/tree/master/Matlab
But the method itself is not that reliable to work on 1k images, let alone 200k images.

**Comment by whitetiger21022014** [comment]
Thanks for your time, the last question
Description for your project: 
"Feature extraction using Gabor filter, redge orientation and SIFT. 
Feature matching using SIFT and RANSAC.
• This project is built using Java, Android and OpenCV. Also built in MATLAB".

**You used many algorithms, so is your analysis accurate?**

P/S: Sorry above question. B/c it is the first time i plan  to use object detection. I can find many face-detection on github with new commits, but with fingerprint-detect I don't see so much)
Thanks you
